Models/ContentType.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace LukaszKijak.Models
{
    public class ContentType
    {
        public string GetContentType(string fileName)
        {
            var type = GetMimeTypes();
            var ext = Path.GetExtension(fileName).ToLowerInvariant();
            return type[ext];
        }

        private Dictionary<string, string> GetMimeTypes()
        {
            Dictionary<string, string> type = new Dictionary<string, string>
            {
                {".txt", "text/plain"},
                {".pdf", "application/pdf"},
                {".cs", "text/cs" },
                {".json", "text/json" },
                {".cshtml", "text/cshtml" },
                {".js", "text/js" },
                {".css", "text/css" },
                {".md", "text/md" },
                {".sln", "application/sln" },
                {".csproj", "application/csproj" },
                {".png", "image/png"},
                {".jpg", "image/jpeg"},
                {".jpeg", "image/jpeg"},
                {".gif", "image/gif"}
            };

            return type;
        }
    }
}

Models/EditModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LukaszKijak.Models
{
    public class EditModel
    {
        public string NewName { get; set; }
        public string OldName { get; set; }
    }
}

Models/ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LukaszKijak.Models
{
    public class ViewModel
    {
        public string Type { get; set; }
        public string Name { get; set; }
        public DateTime ModificationDate { get; set; }
        public double Size { get; set; }
        public string Attribute { get; set; }
        public string MyPath { get; set; }
    }
}

Controllers/ExplorerController.cs
using LukaszKijak.Models;
using LukaszKijak.Service;
using LukaszKijak.Service.SortList;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace LukaszKijak.Controllers
{
    public class ExplorerController : Controller
    {
        private IShowFolder showFolder;

        public ExplorerController(IShowFolder checkFld)
        {
            showFolder = checkFld;
        }

        public ViewResult Index(string path, string sort, string navigation)
        {
            List<ViewModel> list = null;
            string newPath = null;
            
            if (path == "start" && navigation == null)
            {
                AddToNewPath(path);
                newPath = GetMainPath();
                list = showFolder.GetFolderContent(newPath, sort);
                ViewBag.MyNewPath = GetNewPath();
                ViewBag.Root = "rootFolder";
                return View(list);
            }
            else if(path != "start" && navigation == null)
            {
                AddToNewPath(path);
                newPath = GetNewPath();
                list = showFolder.GetFolderContent(newPath, sort);
                ViewBag.MyNewPath = GetNewPath();
                if (GetNewPath() == GetMainPath())
                {
                    ViewBag.Root = "rootFolder";
                }
                return View(list);
            }
            else if (path == null && navigation == "up")
            {
                AddToNewPath(navigation);
                newPath = GetNewPath();
                list = showFolder.GetFolderContent(newPath, sort);
                ViewBag.MyNewPath = GetNewPath();
                if (GetNewPath() == GetMainPath())
                {
                    ViewBag.Root = "rootFolder";
                }
                return View(list);
            }
            list = showFolder.GetFolderContent(GetMainPath(), sort);
            ViewBag.MyNewPath = GetMainPath();
            return View(list);
        }

        public IActionResult Rename(string oldName)
        {
            EditModel model = new EditModel
            {
                OldName = oldName,
                NewName = oldName
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult Rename(EditModel model)
        {
            var filePath = GetNewPath();
            string oldName = filePath + "/" + model.OldName;
            string newName = filePath + "/" + model.NewName;

            try
            {
                System.IO.File.Move(oldName, newName);
                return View("Confirm");
            }
            catch (FileNotFoundException)
            {
                Directory.Move(oldName, newName);
                return View("Confirm");
            }
        }

        public IActionResult OpenFile(string name)
        {
            if (name != null)
            {
                var directory = GetNewPath();

                Process process = new Process();
                process.StartInfo.UseShellExecute = true;
                process.StartInfo.FileName = name;
                process.StartInfo.WorkingDirectory = directory;
                process.Start();
                
                return RedirectToAction("Index");
            }
            return View("ErrorOpen");
            
        }

        public IActionResult DownloadFile(string name)
        {
            ContentType content = new ContentType();
            var fileName = GetNewPath() + "/" + name;
            var type = content.GetContentType(fileName);

            MemoryStream memory = new MemoryStream();
            using (var stream = new FileStream(fileName, FileMode.Open))
            {
                stream.CopyTo(memory);
            }
            memory.Position = 0;
            return File(memory, type, Path.GetFileName(fileName));
        }

        public ActionResult ConfirmDelete(string name)
        {
            TempData["DeleteItemName"] = name;
            return View();
        }

        public IActionResult Delete()
        {
            var name = TempData["DeleteItemName"];
            var itemName = GetNewPath() + "/" + name;
            FileAttributes attr = System.IO.File.GetAttributes(itemName);
            if (attr != FileAttributes.Directory)
            {
                System.IO.File.Delete(itemName);
                return View("ConfirmationDelete");
            }

            if (Directory.GetFileSystemEntries(itemName).Length == 0)
            {
                Directory.Delete(itemName);
                return View("ConfirmationDelete");
            }
            return View("ErrorDelete");
        }


        //**************************** Set and get current path
        public string GetMainPath()
        {
            string path = HttpContext.Session.GetString("mainPath");
            var newPath = path.Replace("\\", "/");
            return newPath;
        }
        public string GetNewPath()
        {
            string newPath = HttpContext.Session.GetString("newPath");
            return newPath;
        }
        public void AddToNewPath(string path)
        {
            string newPath;
            if (path == "start")
            {
                newPath = GetMainPath();
                HttpContext.Session.SetString("newPath", newPath);
            }
            else if (path == "up")
            {
                var cutPath = GetNewPath();
                int counter = cutPath.LastIndexOf("/");
                newPath = cutPath.Substring(0, counter);
                HttpContext.Session.SetString("newPath", newPath);
            }
            else if (path != null)
            {
                newPath = GetNewPath() + "/" + path;
                HttpContext.Session.SetString("newPath", newPath);
            }
        }

    }
}

Controllers/HomeController.cs
using LukaszKijak.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace LukaszKijak.Controllers
{
    public class HomeController : Controller
    {
        public ViewResult Index()
        {
            string mainPath = Directory.GetCurrentDirectory();
            HttpContext.Session.SetString("mainPath", mainPath);
            return View();
        }


    }
}

Views/Explorer/Confirm.cshtml
<div class="bg-light my-height text-center container">
    <br />
    <h1>Zapisano nową nazwę</h1>
    <br />
    <a asp-action="Index" class="btn btn-dark btn-lg">OK</a>
</div>

Views/Explorer/ConfirmDelete.cshtml
<div class="bg-light my-height text-center container">
    <br />
    <h1>Czy napewno chcesz usunąć element ?</h1>
    <br />
    <a asp-action="Delete" class="btn btn-danger btn-lg">OK</a>
    <a asp-action="Index" class="btn btn-dark btn-lg">Anuluj</a>
</div>

Views/Explorer/ConfirmationDelete.cshtml
<div class="bg-light my-height text-center container">
    <br />
    <h1>Element został usunięty.</h1>
    <br />
    <a asp-action="Index" class="btn btn-dark btn-lg">OK</a>
</div>

Views/Explorer/ErrorDelete.cshtml
<div class="bg-light my-height text-center container">
    <br />
    <h1>Folder nie jest pusty i nie może zostać usunięty.</h1>
    <br />
    <a asp-action="Index" class="btn btn-dark btn-lg">OK</a>
</div>

Views/Explorer/ErrorOpen.cshtml
<div class="bg-light my-height text-center container">
    <br />
    <h1>Nie udało się otworzyć pliku.</h1>
    <br />
    <a asp-action="Index" class="btn btn-dark btn-lg">OK</a>
</div>

Views/Explorer/Index.cshtml
@model List<ViewModel>

<div class="bg-light my-height container">
    <br />
    <h4>Eksplorator plików</h4>
    <br /><br />
    <p>Tu powinien być link : @ViewBag.MyNewPath</p>
    <table class="table table-bordered">
        <tr>
            <th>
                Typ
                <div class="my-div-sort">
                    <a asp-action="Index" asp-route-sort="Type">
                        <img src="~/image/sortAscending.png" title="Sortuj rosnąco" class="my-img-sort" />
                    </a>
                    <a asp-action="Index" asp-route-sort="TypeDescending">
                        <img src="~/image/sortDescending.png" title="Sortuj malejąco" class="my-img-sort" />
                    </a>
                </div>
            </th>
            <th>
                Nazwa
                <div class="my-div-sort">
                    <a asp-action="Index" asp-route-sort="Name">
                        <img src="~/image/sortAscending.png" title="Sortuj rosnąco" class="my-img-sort" />
                    </a>
                    <a asp-action="Index" asp-route-sort="NameDescending">
                        <img src="~/image/sortDescending.png" title="Sortuj malejąco" class="my-img-sort" />
                    </a>
                </div>
            </th>
            <th>
                Data modyfikacji
                <div class="my-div-sort">
                    <a asp-action="Index" asp-route-sort="Modification">
                        <img src="~/image/sortAscending.png" title="Sortuj rosnąco" class="my-img-sort" />
                    </a>
                    <a asp-action="Index" asp-route-sort="ModificationDescending">
                        <img src="~/image/sortDescending.png" title="Sortuj malejąco" class="my-img-sort" />
                    </a>
                </div>
            </th>
            <th>
                Rozmiar (KB)
                <div class="my-div-sort">
                    <a asp-action="Index" asp-route-sort="Size">
                        <img src="~/image/sortAscending.png" title="Sortuj rosnąco" class="my-img-sort" />
                    </a>
                    <a asp-action="Index" asp-route-sort="SizeDescending">
                        <img src="~/image/sortDescending.png" title="Sortuj malejąco" class="my-img-sort" />
                    </a>
                </div>
            </th>
            <th>
                Atrybuty
                <div class="my-div-sort">
                    <a asp-action="Index" asp-route-sort="Attribute">
                        <img src="~/image/sortAscending.png" title="Sortuj rosnąco" class="my-img-sort" />
                    </a>
                    <a asp-action="Index" asp-route-sort="AttributeDescending">
                        <img src="~/image/sortDescending.png" title="Sortuj malejąco" class="my-img-sort" />
                    </a>
                </div>
            </th>
            <th>Akcja</th>
        </tr>
        @if (ViewBag.Root != "rootFolder")
        {
            <tr>
                <td>
                    <img src="~/image/folder.png" class="my-img" />
                </td>
                <td>
                    <a asp-action="Index" asp-route-navigation="up">...</a>
                </td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        }

        @foreach (var obj in Model)
        {
            <tr>
                <td>
                    @if (obj.Type == "folder")
                    {
                        <a asp-action="Rename" asp-route-oldName="@obj.Name"><img src="~/image/folder.png" class="my-img" /></a>
                    }
                    else
                    {
                        <a asp-action="Rename" asp-route-oldName="@obj.Name"><img src="~/image/file.png" class="my-img" /></a>
                    }
                </td>
                <td>
                    @if (obj.Type == "folder")
                    {
                        <a asp-action="Index" asp-route-path="@obj.Name">@obj.Name</a>
                    }
                    else
                    {
                        <a asp-action="OpenFile" asp-route-name="@obj.Name">@obj.Name</a>
                    }
                </td>
                <td>@obj.ModificationDate</td>
                <td>
                    @if (obj.Type != "folder")
                    {
                        @obj.Size
                    }
                </td>
                <td>@obj.Attribute</td>
                <td>
                    <a asp-action="ConfirmDelete" asp-route-name="@obj.Name"><img src="~/image/trash.png" class="my-img" /></a>
                    @if (obj.Type != "folder")
                    {
                        <a asp-action="DownloadFile" asp-route-name="@obj.Name"><img src="~/image/download.png" class="my-img" /></a>
                    }
                </td>
            </tr>
        }

    </table>
</div>

Views/Explorer/Rename.cshtml
@model EditModel

<div class="bg-light my-height text-center container">
    <br />
    <h1>Zmiana nazwy</h1>
    <br />
    <form asp-action="Rename" method="post">
        <label asp-for="NewName">Nowa nazwa</label>
        <input asp-for="NewName" class="form-control" />
        <input asp-for="OldName" type="hidden" value="@Model.OldName" />
        <br />
        <button type="submit" class="btn btn-lg btn-info">Zapisz</button>
        <a asp-action="Index" class="btn btn-lg btn-danger">Anuluj</a> 
    </form>
</div>

Views/Home/Index.cshtml
<div class="my-home-bg my-height text-center container-fluid">
    <br />
    <h1>Dzień dobry</h1>
    <br />
    <a asp-action="Index" asp-controller="Explorer" asp-route-path="start" class="btn btn-dark btn-lg">Eksplorator</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
    <title>Łukasz kijak</title>
</head>
<body>
    <div class="bg-light">
        @RenderBody()
    </div>
</body>
</html>